# permissions to do viewer cdapmasters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdapmaster-viewer-role
rules:
- apiGroups:
  - cdap.cdap.io
  resources:
  - cdapmasters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdap.cdap.io
  resources:
  - cdapmasters/status
  verbs:
  - get
