apiVersion: cdap.cdap.io/v1alpha1
kind: CDAPMaster
metadata:
  labels:
    cdap.version: "6.0.0"
  name: owooo
spec:
  image: gcr.io/cloud-data-fusion-images/cloud-data-fusion:6.0.1.0
  userInterfaceImage: gcr.io/cloud-data-fusion-images/cloud-data-fusion-ui:6.0.1.0
  upgradeImage: gcr.io/jay-test-dev/uwuuso:latest
  appFabric:
    resources:
      requests:
        memory: "3Gi"
        cpu: "2000m"
  logs:
    resources:
      requests:
        memory: "2500Mi"
        cpu: "2000m"
    storageSize: "125Gi"
  messaging:
    resources:
      requests:
        memory: "2500Mi"
        cpu: "2000m"
    storageSize: "125Gi"
  metadata:
    resources:
      requests:
        memory: "2500Mi"
        cpu: "1500m"
  metrics:
    resources:
      requests:
        memory: "2500Mi"
        cpu: "1500m"
    storageSize: "125Gi"
  preview:
    resources:
      requests:
        memory: "2500Mi"
        cpu: "1500m"
    storageSize: "125Gi"
  userInterface:
    replicas: 1
  router:
    replicas: 1
  securitySecret: cdap-security
  locationURI: gs://somebucket
  config:
    enable.preview: "true"
    data.storage.implementation: postgresql
    data.storage.sql.jdbc.connection.url: <JDBC Connection String>
    data.storage.sql.jdbc.driver.name: org.postgresql.Driver
    metadata.storage.implementation: elastic
    metadata.elasticsearch.cluster.hosts: escluster-master:9200
