apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Service.Name}}
  namespace: {{.Master.Namespace}}
  labels:
    {{range $k,$v := .Labels }}
    {{$k}}: {{$v}}
    {{end}}
  annotations:
    {{range $k,$v := .Annotations }}
    {{$k}}: {{$v}}
    {{end}}
spec:
  selector:
    matchLabels:
      cdap.container: app-fabric
  replicas: 1
  template:
    metadata:
      labels:
        cdap.container: app-fabric
    spec:
      serviceAccountName: cdap
      initContainers:
        - image: gcr.io/cloud-data-fusion-images/cloud-data-fusion:6.0.0-SNAPSHOT
          name: create-storage
          args: ["co.cask.cdap.master.environment.k8s.StorageMain"]
          imagePullPolicy: Always
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
            - name: cdap-conf
              mountPath: /etc/cdap/conf
              readOnly: true
            - name: cdap-security
              mountPath: /etc/cdap/security
              readOnly: true
            - name: hadoop-conf
              mountPath: /etc/hadoop/conf
              readOnly: true
      containers:
        - image: gcr.io/cloud-data-fusion-images/cloud-data-fusion:6.0.0-SNAPSHOT
          args: ["co.cask.cdap.master.environment.k8s.AppFabricServiceMain", "--env=k8s"]
          name: cdap-app-fabric
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1.6Gi"
              cpu: "400m"
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
            - name: cdap-conf
              mountPath: /etc/cdap/conf
              readOnly: true
            - name: cdap-security
              mountPath: /etc/cdap/security
              readOnly: true
            - name: hadoop-conf
              mountPath: /etc/hadoop/conf
              readOnly: true
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "pod.labels.properties"
                fieldRef:
                  fieldPath: metadata.labels
        - name: cdap-conf
          configMap:
            name: cdap-conf
        - name: cdap-security
          secret:
            secretName: cdap-security
        - name: hadoop-conf
          configMap:
            name: hadoop-conf
