# Copyright 2019 The CDAP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Base.Name}}
  namespace: {{.Base.Namespace}}
{{if .Base.Labels}}
  labels:
    {{range $k,$v := .Base.Labels}}
    {{$k}}: {{$v}}
    {{end}}
{{end}}
spec:
  selector:
    matchLabels:
      {{range $k,$v := .Base.Labels}}
      {{$k}}: {{$v}}
      {{end}}
  replicas: {{.Base.Replicas}}
  template:
    metadata:
      labels:
        {{range $k,$v := .Base.Labels }}
        {{$k}}: {{$v}}
        {{end}}
    spec:
    {{if .Base.ServiceAccountName}}
      serviceAccountName: {{.Base.ServiceAccountName}}
    {{end}}
    {{if .Base.NodeSelector}}
      nodeSelector:
        {{range $k,$v := .Base.NodeSelector}}
        {{$k}}: '{{$v}}'
        {{end}}
    {{end}}
    {{if .Base.RuntimeClassName}}
      runtimeClassName: {{.Service.RuntimeClassName}}
    {{end}}
    {{if .Base.PriorityClassName}}
      priorityClassName: {{.Service.PriorityClassName}}
    {{end}}
    {{range $c := .Containers}}
      containers:
        - name: {{$c.Name}}
          image: {{$c.Image}}
          workingDir: "/opt/cdap/ui"
          command: ["bin/node"]
          args: ["index.js", "start"]
        {{if $c.ImagePullPolicy}}
          imagePullPolicy: {{$c.ImagePullPolicy}}
        {{end}}
          resources: {}
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: cdap-conf
              mountPath: /etc/cdap/conf
              readOnly: true
            - name: hadoop-conf
              mountPath: /etc/hadoop/conf
              readOnly: true
      {{end}}
      volumes:
        - name: cdap-conf
          configMap:
            name: {{.Base.CConf}}
        - name: hadoop-conf
          configMap:
            name: {{.Base.HConf}}
